version: '3.8'

services:
  people-tracker-yolo:
    build: .
    entrypoint: python3 setup.py test
    volumes:
      - .:/opt/src
#      - ./yolov5x.pt:/opt/src/weights/yolov5x.pt
#      - ./ckpt.t7:/opt/src/deep_sort/deep/checkpoint/ckpt.t7
